### ISSUE TITLE
New Manim Version not compatible

### ISSUE THREAD

**Issue by Adkoda-777** [raghavg123/chanim#15]
Hello. I have recently found the chanim package here on GitHub. I really love the package and the idea to use the chemfig library from LaTex. I immediately installed it via pip. Then of course the packages mactex and ffmpg (I am on a Mac). But for some reason some classes used by the Chanim package do not exist anymore (e.g. the TexTemplate Class. Am I using the wrong version of manim or am I missing something?

**Comment by Adkoda-777** [comment]
I solved it

**Comment by denisov0gleb** [comment]
@AdrianHTML Hello! Could you please provide more information? How did you solve that problem?
