### ISSUE TITLE
Bonds not displayed

### ISSUE THREAD

**Issue by alexander-schoch-github** [raghavg123/chanim#3]
After compiling 

```
class tikz(Scene):
    def construct(self):
        testobject = ChemObject("-[:30](=[2]O)-[:30]OH")
        self.play(Write(testobject))
        self.wait(3)
```

the resulting image looks like compiled by pure `manim`:

![aceticacid](https://user-images.githubusercontent.com/59538716/71784454-f445e080-2ff3-11ea-84c2-9feac036cb85.png)

**Comment by kilacoda** [comment]
Works for me though:
![tikz](https://user-images.githubusercontent.com/14952412/71784519-603b3f80-301a-11ea-85da-59f24cf42e0a.png)
Could you show the `.tex` file, please?

**Comment by alexander-schoch-github** [comment]
Of course I forgot the minus sign...

corresponding `.tex`-file:
```
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\usepackage{tikz}
\usetikzlibrary{arrows}
\usetikzlibrary{shapes.geometric}
\usepackage{chemfig}
\usepackage{mhchem}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

\begin{align*}
\setchemfig{atom sep = 2em}
\chemfig{-[:30](=[2]O)-[:-30]OH}
\end{align*}

\end{document}
```

I don't see anything wrong with it at a short glance.

**Comment by alexander-schoch-github** [comment]
Update: After some messing around, I found out that the compilation from `.dvi` to `.svg` failed. This issue could be resolved by using `\documentclass[preview,dvisvgm]{standalone}` in the preamble. Now, the `.svg` file is generated correctly.

However, afterwards, this `.svg` file is not inserted into the video/image correctly, as seen here (code below):

![ExampleTikz](https://user-images.githubusercontent.com/59538716/71877457-7daaff00-3129-11ea-942a-cd8ea52e3f7b.png)

This appears to be a general manim problem, though, which is why I opened an issue on `3b1b/manim`.

As this problem does not occur in your case, I am assuming that it only happens on linux-based operating systems.

Code for image above:

```
from manimlib.imports import *

class TikzMobject(TextMobject):
    CONFIG = {
        "stroke_width": 3,
        "fill_opacity": 0,
        "stroke_opacity": 1,
    }

class ExampleTikz(Scene):
    def construct(self):
        circuit = TikzMobject(r"""
            \begin{tikzpicture}
                \draw (0,0) -- (1,0);
                \node at (1,0) {sometext};
            \end{tikzpicture}
            """
            )
        self.play(Write(circuit))
        self.wait()
```
