### ISSUE TITLE
Examples usage?

### ISSUE THREAD

**Issue by hemanta212** [raghavg123/chanim#8]
Would love some code examples on usage of this lib. Maybe consider adding source code of videos you produce in a folder?

**Comment by kilacoda-old** [comment]
Hi!

Yeah I've thought about it, haven't really had time (and ideas) to write new videos. I guess for now I'll add some basic examples in Discussions (hopefully (someday) ).

> Maybe consider adding source code of videos you produce in a folder?

If I continue to make more videos in the future, sure, I'll put them in a separate repo. I don't see the point of making one for a single file though.

**Comment by hemanta212** [comment]
> I don't see the point of making one for a single file though.

it would be fine if you can just drop it in a separate temp branch or heck even as a pastebin link.

**Comment by kilacoda-old** [comment]
https://github.com/kilacoda/videos

All right, I made a new repo for the video code. I'll be adding examples for chanim sometime this week or the next.

**Comment by hemanta212** [comment]
wow, great thanks :)
